name: Send email with PDF file

on:
  push:
    paths:
      - '*.pdf'
      - '*.epub' 


env: 
  DISABLE_DEBUG: false

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check for new PDF file	
        id: check_pdf	
        run: |	
          pdf_count=$(git diff --name-only HEAD^ HEAD --diff-filter=A -- '*.pdf' | wc -l)	
          if [ "$pdf_count" -gt "0" ]; then	
            echo "New PDF file detected!"	
            echo "::set-output name=pdf_found::true"	
          else	
            echo "No new PDF files detected."	
            echo "::set-output name=pdf_found::false"	
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postfix mailutils # caching needed
      
      - name: Debug repository contents
        if: env.DISABLE_DEBUG = 'false'
        run: |
          echo "check origin contents"
          ls -R ${GITHUB_WORKSPACE}
          echo "check current branch" 
          git rev-parse --abbrev-ref HEAD
          echo "check origin status"  
          git status 
          echo "check git diff"
          git diff --name-only HEAD^ HEAD --diff-filter=A -- '*.pdf' # trigger only pdf files througout repo+lib directories. filter=A is mandatory"  
      
 
      - name: Zip library
        run: | 
          chmod +x ./scripts
          echo "zipping initiated" 
          ./scripts/libzip.sh
          echo "zipping succesful: zip added to libzip"        
      
      - name: Send mail
        if: ${{ steps.check_pdf.outputs.pdf_found == 'true' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'github-kindler: you have a new item in your catalog!'
          body: 'this push was autogenerated because github-kindler agent found a change in your main repository'
          from: ${{ secrets.EMAIL_SRC }}
          to: ${{ secrets.EMAIL_DST }}
          attachments: ${{ github.workspace }}/lib/new/*.pdf
       
      - name: debug
        run: |
          echo "PDF found: ${{ steps.check_pdf.outputs.pdf_found }}"
