name: Restore in prod

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "CONFIRM" to proceed with restoring the database.'
        required: true
        default: 'Type here'

jobs:
  restore-db:
    runs-on: ubuntu-latest
    environment:
      name: prod  
      url: ${{ steps.restore.outputs.db-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
   

      - name: Restore Database
        id: restore
        run: |

          echo "::set-output name=db-url::http://example.com/db-status" 
          echo "restoration completed."

      - name: Notify completion
        run: echo "restoration to production has been successfully completed."

